export enum SocialCategory {
    GENERAL = "GENERAL",
    SC = "SC",
    ST = "ST",
    OBC = "OBC",
}
  
export enum Gender {
    MALE = "MALE",
    FEMALE = "FEMALE",
    OTHERS = "OTHERS",
}
  
export enum ActivityCategory {
    MANUFACTURING = "MANUFACTURING",
    SERVICES = "SERVICES",
    TRADING = "TRADING",
}
  
export enum TypeOfOrganisation {
    CO_OPERATIVE = "CO_OPERATIVE",
    HINDU_UNDIVIDED_FAMILY = "HINDU_UNDIVIDED_FAMILY",
    LIMITED_LIABILITY_PARTNERSHIP = "LIMITED_LIABILITY_PARTNERSHIP",
    OTHERS = "OTHERS",
    PARTNERSHIP = "PARTNERSHIP",
    PRIVATE_LIMITED_COMPANY = "PRIVATE_LIMITED_COMPANY",
    PROPRIETARY = "PROPRIETARY",
    PUBLIC_LIMITED_COMPANY = "PUBLIC_LIMITED_COMPANY",
    SELF_HELP_GROUP = "SELF_HELP_GROUP",
    SOCIETY = "SOCIETY",
    TRUST = "TRUST",
}
