export enum OTPVerificationType {
  VERIFY_SESSION = "verify-session",
  CONFIRM_REGISTRATION = "confirm-registration",
}

export enum UdyamRegistrationStage {
    SESSION_INITIATED = "SESSION_INITIATED",
    SESSION_INITIATION_SUCCESSFUL = "SESSION_INITIATION_SUCCESSFUL",
    SESSION_INITIATION_FAILED = "SESSION_INITIATION_FAILED",
    SESSION_VERIFICATION_OTP_RECEIVED = "SESSION_VERIFICATION_OTP_RECEIVED",
    SESSION_VERIFICATION_OTP_SUCCESSFUL = "SESSION_VERIFICATION_OTP_SUCCESSFUL",
    SESSION_VERIFICATION_OTP_FAILED = "SESSION_VERIFICATION_OTP_FAILED",
    SESSION_VERIFICATION_OTP_FAILED_ACTIVE_SESSION = "SESSION_VERIFICATION_OTP_FAILED_ACTIVE_SESSION",
    SESSION_DETAILS_RECEIVED = "SESSION_DETAILS_RECEIVED",
    SESSION_DETAILS_ADDITION_SUCCESSFUL = "SESSION_DETAILS_ADDITION_SUCCESSFUL",
    SESSION_DETAILS_ADDITION_FAILED = "SESSION_DETAILS_ADDITION_FAILED",
    SESSION_DETAILS_ADDITION_FAILED_ACTIVE_SESSION = "SESSION_DETAILS_ADDITION_FAILED_ACTIVE_SESSION",
    SESSION_CONFIRMATION_OTP_RECEIVED = "SESSION_CONFIRMATION_OTP_RECEIVED",
    SESSION_CONFIRMATION_OTP_SUCCESSFUL = "SESSION_CONFIRMATION_OTP_SUCCESSFUL",
    SESSION_CONFIRMATION_OTP_FAILED_ACTIVE_SESSION = "SESSION_CONFIRMATION_OTP_FAILED_ACTIVE_SESSION",
    SESSION_CONFIRMATION_OTP_FAILED = "SESSION_CONFIRMATION_OTP_FAILED",
    SESSION_RESEND_CONFIRMATION_OTP_RECIEVED = "SESSION_RESEND_CONFIRMATION_OTP_RECIEVED",
    SESSION_RESEND_CONFIRMATION_OTP_SUCCESSFUL = "SESSION_RESEND_CONFIRMATION_OTP_SUCCESSFUL",
    SESSION_RESEND_CONFIRMATION_OTP_FAILED = "SESSION_RESEND_CONFIRMATION_OTP_FAILED",
}